# This file tells GitHub to enable Dependabot version updates
# For more info: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "yourusername"  # Replace with actual maintainer usernames
    assignees:
      - "yourusername"
    commit-message:
      prefix: "chore(backend)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    # Group minor and patch updates together
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "jest*"
          - "nodemon"
          - "ts-*"
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "jest*"
          - "nodemon"
          - "ts-*"

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend/BadmintonGroup"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "yourusername"
    assignees:
      - "yourusername"
    commit-message:
      prefix: "chore(frontend)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    groups:
      react-native:
        patterns:
          - "react*"
          - "expo*"
          - "@expo/*"
          - "@react-*"
      development-tools:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "jest*"
          - "typescript"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependencies"
      - "ci"