name: Bug Report
description: Report a bug to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before proceeding
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have read the documentation
          required: true
        - label: This is not a duplicate issue
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Backend API
        - Frontend Mobile App
        - Database
        - Authentication
        - Real-time features
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of BadmintonGroup are you using?
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you using?
      options:
        - iOS
        - Android
        - Web
        - Backend Server
        - Multiple platforms
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem
      placeholder: Drag and drop images/videos here or paste links

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g. iOS 17.0, Android 13, macOS 14.0]
        - Device: [e.g. iPhone 15, Samsung Galaxy S23]
        - App Version: [e.g. 1.0.0]
        - Node.js Version: [e.g. 18.17.0] (for backend issues)

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: Please provide any relevant logs or error messages
      placeholder: Paste logs here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...