name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before proceeding
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: I have read the project roadmap
          required: true
        - label: This is not a duplicate request
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - User Interface
        - Game Management
        - Player Management
        - Session Management
        - Authentication
        - Real-time Features
        - Mobile App
        - Backend API
        - Performance
        - Security
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my usage
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or pain point this feature would address...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: What alternatives have you considered?

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases for this feature
      placeholder: |
        1. As a [user type], I want to [goal] so that [benefit]
        2. When [situation], I need to [action] because [reason]

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Designs
      description: If you have any mockups, wireframes, or design ideas, please share them
      placeholder: Drag and drop images here or paste links

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Minor change or addition
        - Medium - Moderate development effort
        - Complex - Significant development effort
        - Very Complex - Major architectural changes
        - Unknown - I'm not sure

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Areas
      description: Which parts of the system would this feature affect? (Select all that apply)
      options:
        - label: Frontend Mobile App
        - label: Backend API
        - label: Database Schema
        - label: Real-time Communication
        - label: Authentication System
        - label: User Interface
        - label: Documentation
        - label: Testing

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that might be helpful...